/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AirQualityRouteImport } from './routes/air-quality'
import { Route as EnvironmentalRouteImport } from './routes/environmental'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ParticulateRouteImport } from './routes/particulate'
import { Route as PowerRouteImport } from './routes/power'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AirQualityRoute = AirQualityRouteImport.update({
  id: '/air-quality',
  path: '/air-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentalRoute = EnvironmentalRouteImport.update({
  id: '/environmental',
  path: '/environmental',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticulateRoute = ParticulateRouteImport.update({
  id: '/particulate',
  path: '/particulate',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerRoute = PowerRouteImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/air-quality': typeof AirQualityRoute
  '/environmental': typeof EnvironmentalRoute
  '/logs': typeof LogsRoute
  '/particulate': typeof ParticulateRoute
  '/power': typeof PowerRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/air-quality': typeof AirQualityRoute
  '/environmental': typeof EnvironmentalRoute
  '/logs': typeof LogsRoute
  '/particulate': typeof ParticulateRoute
  '/power': typeof PowerRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/air-quality': typeof AirQualityRoute
  '/environmental': typeof EnvironmentalRoute
  '/logs': typeof LogsRoute
  '/particulate': typeof ParticulateRoute
  '/power': typeof PowerRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/air-quality'
    | '/environmental'
    | '/logs'
    | '/particulate'
    | '/power'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/air-quality'
    | '/environmental'
    | '/logs'
    | '/particulate'
    | '/power'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/air-quality'
    | '/environmental'
    | '/logs'
    | '/particulate'
    | '/power'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirQualityRoute: typeof AirQualityRoute
  EnvironmentalRoute: typeof EnvironmentalRoute
  LogsRoute: typeof LogsRoute
  ParticulateRoute: typeof ParticulateRoute
  PowerRoute: typeof PowerRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-quality': {
      id: '/air-quality'
      path: '/air-quality'
      fullPath: '/air-quality'
      preLoaderRoute: typeof AirQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environmental': {
      id: '/environmental'
      path: '/environmental'
      fullPath: '/environmental'
      preLoaderRoute: typeof EnvironmentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/particulate': {
      id: '/particulate'
      path: '/particulate'
      fullPath: '/particulate'
      preLoaderRoute: typeof ParticulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirQualityRoute: AirQualityRoute,
  EnvironmentalRoute: EnvironmentalRoute,
  LogsRoute: LogsRoute,
  ParticulateRoute: ParticulateRoute,
  PowerRoute: PowerRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
